In [3]:
import numpy as np
import pandas as pd

In [4]:
arr = np.array([1200, 2500, 1800, 3200, 4500])

arr

array([1200, 2500, 1800, 3200, 4500])

In [12]:
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

1
(5,)
5
int64

In [23]:
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(arr * 1.10)
print(arr[arr > 2000])

13200
1200
4500
2640.0
[1320. 2750. 1980. 3520. 4950.]
[2500 3200 4500]

In [24]:
arr2 = np.array([
    ["Vagabond", 9],
    ["Warrior", 1],
    ["Hero", 7],
    ["Bandit", 5],
    ["Astrologer", 6]
])

arr2

array([['Vagabond', '9'],
       ['Warrior', '1'],
       ['Hero', '7'],
       ['Bandit', '5'],
       ['Astrologer', '6']], dtype='<U21')

In [25]:
print(arr2.ndim)
print(arr2.shape)
print(arr2.size)
print(arr2.dtype)

2
(5, 2)
10
<U21

In [26]:
classes = np.array(["Vagabond", "Warrior", "Hero", "Bandit", "Astrologer"])
levels = np.array([9, 1, 7, 5, 6])

print(np.sum(levels))
print(np.mean(levels))
print(np.min(levels))
print(np.max(levels))

28
5.6
1
9

In [27]:
df = pd.read_csv("elden_ring_classes.csv")

In [28]:
print(df.head())

        Class  Vigor  Mind  Endurance  Strength  Dexterity  Intelligence  \
0    Vagabond     15    10         11        14         13             9
1     Warrior     11    12         11        10         16            10
2        Hero     14     9         12        16          9             7
3      Bandit     10    11         10         9         13             9
4  Astrologer      9    15          9         8         12            16

   Faith  Arcane
0      9       7
1      8       9
2      8      11
3      8      14
4      7       9

In [29]:
print(df.head(3))

      Class  Vigor  Mind  Endurance  Strength  Dexterity  Intelligence  Faith  \
0  Vagabond     15    10         11        14         13             9      9
1   Warrior     11    12         11        10         16            10      8
2      Hero     14     9         12        16          9             7      8

   Arcane
0       7
1       9
2      11

In [30]:
print(df.tail())

       Class  Vigor  Mind  Endurance  Strength  Dexterity  Intelligence  \
5    Prophet     10    14          8        11         10             7
6    Samurai     12    11         13        12         15             9
7   Prisoner     11    12         11        11         14            14
8  Confessor     10    13         10        12         12             9
9     Wretch     10    10         10        10         10            10

   Faith  Arcane
5     16      10
6      8       8
7      6       9
8     14       9
9     10      10

In [32]:
print(df.shape)
print(df.columns)
print(df.info())

(10, 9)
Index(['Class', 'Vigor', 'Mind', 'Endurance', 'Strength', 'Dexterity',
       'Intelligence', 'Faith', 'Arcane'],
      dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Class         10 non-null     str
 1   Vigor         10 non-null     int64
 2   Mind          10 non-null     int64
 3   Endurance     10 non-null     int64
 4   Strength      10 non-null     int64
 5   Dexterity     10 non-null     int64
 6   Intelligence  10 non-null     int64
 7   Faith         10 non-null     int64
 8   Arcane        10 non-null     int64
dtypes: int64(8), str(1)
memory usage: 852.0 bytes
None

In [33]:

print(df.describe())

           Vigor       Mind  Endurance   Strength  Dexterity  Intelligence  \
count  10.000000  10.000000  10.000000  10.000000  10.000000     10.000000
mean   11.200000  11.700000  10.500000  11.300000  12.400000     10.000000
std     1.932184   1.888562   1.433721   2.359378   2.270585      2.867442
min     9.000000   9.000000   8.000000   8.000000   9.000000      7.000000
25%    10.000000  10.250000  10.000000  10.000000  10.500000      9.000000
50%    10.500000  11.500000  10.500000  11.000000  12.500000      9.000000
75%    11.750000  12.750000  11.000000  12.000000  13.750000     10.000000
max    15.000000  15.000000  13.000000  16.000000  16.000000     16.000000

           Faith     Arcane
count  10.000000  10.000000
mean    9.400000   9.600000
std     3.169297   1.897367
min     6.000000   7.000000
25%     8.000000   9.000000
50%     8.000000   9.000000
75%     9.750000  10.000000
max    16.000000  14.000000

In [34]:
df.isnull()

,Class,Vigor,Mind,Endurance,Strength,Dexterity,Intelligence,Faith,Arcane
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False

In [35]:
df.isnull().sum()

Class           0
Vigor           0
Mind            0
Endurance       0
Strength        0
Dexterity       0
Intelligence    0
Faith           0
Arcane          0
dtype: int64

In [36]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [38]:
stats = ["Vigor", "Mind", "Endurance", "Strength",
         "Dexterity", "Intelligence", "Faith", "Arcane"]

df["Level"] = df[stats].sum(axis=1) - 79

df

,Class,Vigor,Mind,Endurance,Strength,Dexterity,Intelligence,Faith,Arcane,Level
0,Vagabond,15,10,11,14,13,9,9,7,9
1,Warrior,11,12,11,10,16,10,8,9,8
2,Hero,14,9,12,16,9,7,8,11,7
3,Bandit,10,11,10,9,13,9,8,14,5
4,Astrologer,9,15,9,8,12,16,7,9,6
5,Prophet,10,14,8,11,10,7,16,10,7
6,Samurai,12,11,13,12,15,9,8,8,9
7,Prisoner,11,12,11,11,14,14,6,9,9
8,Confessor,10,13,10,12,12,9,14,9,10
9,Wretch,10,10,10,10,10,10,10,10,1

In [39]:
df[df["Strength"] > 12]

,Class,Vigor,Mind,Endurance,Strength,Dexterity,Intelligence,Faith,Arcane,Level
0,Vagabond,15,10,11,14,13,9,9,7,9
2,Hero,14,9,12,16,9,7,8,11,7

In [40]:
df[(df["Vigor"] > 10) & (df["Endurance"] > 10)]

,Class,Vigor,Mind,Endurance,Strength,Dexterity,Intelligence,Faith,Arcane,Level
0,Vagabond,15,10,11,14,13,9,9,7,9
1,Warrior,11,12,11,10,16,10,8,9,8
2,Hero,14,9,12,16,9,7,8,11,7
6,Samurai,12,11,13,12,15,9,8,8,9
7,Prisoner,11,12,11,11,14,14,6,9,9

In [42]:
df[(df["Vigor"] > 10) | (df["Level"] >= 9)]

,Class,Vigor,Mind,Endurance,Strength,Dexterity,Intelligence,Faith,Arcane,Level
0,Vagabond,15,10,11,14,13,9,9,7,9
1,Warrior,11,12,11,10,16,10,8,9,8
2,Hero,14,9,12,16,9,7,8,11,7
6,Samurai,12,11,13,12,15,9,8,8,9
7,Prisoner,11,12,11,11,14,14,6,9,9
8,Confessor,10,13,10,12,12,9,14,9,10

In [43]:
df.groupby("Class")["Strength"].sum()

Class
Astrologer     8
Bandit         9
Confessor     12
Hero          16
Prisoner      11
Prophet       11
Samurai       12
Vagabond      14
Warrior       10
Wretch        10
Name: Strength, dtype: int64

In [47]:
df[df["Intelligence"] == df["Intelligence"].max()]

,Class,Vigor,Mind,Endurance,Strength,Dexterity,Intelligence,Faith,Arcane,Level
4,Astrologer,9,15,9,8,12,16,7,9,6

In [48]:
df.groupby("Class")["Intelligence"].mean()

Class
Astrologer    16.0
Bandit         9.0
Confessor      9.0
Hero           7.0
Prisoner      14.0
Prophet        7.0
Samurai        9.0
Vagabond       9.0
Warrior       10.0
Wretch        10.0
Name: Intelligence, dtype: float64

In [51]:
print(df["Intelligence"].max())

16